"""Hermass Factor Registry - metadata governance for factors and blocks."""

from hermass_platform.factors.block_schema import (
    BlockSpec,
    BlockType,
    ContextRequirement,
    ParameterMode,
    ParameterSpace,
    ParameterSpec,
)
from hermass_platform.factors.catalog_loader import CatalogLoader, load_catalogs
from hermass_platform.factors.exceptions import (
    BlockNotFoundError,
    BlockValidationError,
    CatalogLoadError,
    DataUnavailableError,
    DuplicateBlockError,
    DuplicateEvidenceError,
    DuplicateFactorError,
    DuplicateSourceError,
    EvidenceGateError,
    FactorNotFoundError,
    FactorValidationError,
    FutureLeakageError,
    InvalidSourceTypeError,
    RegistryError,
    RegistryValidationError,
    SourceNotFoundError,
    SourceValidationError,
)
from hermass_platform.factors.factor_schema import (
    ComputeEngine,
    DataAvailability,
    DslExposure,
    FactorDirection,
    FactorFrequency,
    FactorLevel,
    FactorSpec,
    FactorStatus,
    FutureLeakageRisk,
    PreviewSupport,
    ProductionGate,
    derive_factor_gate,
)
from hermass_platform.factors.registry import (
    BlockRegistry,
    EvidenceRegistry,
    FactorRegistry,
    RegistryValidator,
    SourceRegistry,
)
from hermass_platform.factors.source_schema import (
    ApplicableMarket,
    Evidence,
    EvidenceLevel,
    EvidenceStatus,
    EvidenceType,
    FactorSource,
    FailureMode,
    MetricRef,
    Reliability,
    SourceType,
    ValidationStatus,
)

__all__ = [
    # Schema
    "FactorSource",
    "Evidence",
    "MetricRef",
    "FactorSpec",
    "BlockSpec",
    "ParameterSpec",
    "ParameterSpace",
    # Enums
    "SourceType",
    "Reliability",
    "ApplicableMarket",
    "EvidenceLevel",
    "EvidenceType",
    "EvidenceStatus",
    "ValidationStatus",
    "FailureMode",
    "FactorStatus",
    "FactorLevel",
    "FactorFrequency",
    "FactorDirection",
    "ComputeEngine",
    "PreviewSupport",
    "DslExposure",
    "DataAvailability",
    "FutureLeakageRisk",
    "ProductionGate",
    "BlockType",
    "ContextRequirement",
    "ParameterMode",
    # Registry
    "SourceRegistry",
    "FactorRegistry",
    "BlockRegistry",
    "EvidenceRegistry",
    "RegistryValidator",
    # Loader
    "CatalogLoader",
    "load_catalogs",
    # Exceptions
    "RegistryError",
    "DuplicateSourceError",
    "DuplicateFactorError",
    "DuplicateBlockError",
    "DuplicateEvidenceError",
    "SourceNotFoundError",
    "FactorNotFoundError",
    "BlockNotFoundError",
    "InvalidSourceTypeError",
    "EvidenceGateError",
    "FutureLeakageError",
    "DataUnavailableError",
    "SourceValidationError",
    "FactorValidationError",
    "BlockValidationError",
    "CatalogLoadError",
    "RegistryValidationError",
    # Functions
    "derive_factor_gate",
]
